"""doc service initial

Revision ID: 823cdc53bdaa
Revises: 
Create Date: 2026-09-22 18:48:12.892401
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '823cdc53bdaa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_key', sa.String(length=320), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'sha256', name='uq_document_user_sha'),
    schema='docs'
    )
    op.create_index(op.f('ix_docs_documents_sha256'), 'documents', ['sha256'], unique=False, schema='docs')
    op.create_index(op.f('ix_docs_documents_status'), 'documents', ['status'], unique=False, schema='docs')
    op.create_index(op.f('ix_docs_documents_user_key'), 'documents', ['user_key'], unique=False, schema='docs')
    op.create_index('ix_documents_user_kind', 'documents', ['user_key', 'kind'], unique=False, schema='docs')
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_key', sa.String(length=320), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['docs.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docs'
    )
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, schema='docs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_user_document', 'document_chunks', ['user_key', 'document_id'], unique=False, schema='docs')
    op.create_index(op.f('ix_docs_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='docs')
    op.create_index(op.f('ix_docs_document_chunks_user_key'), 'document_chunks', ['user_key'], unique=False, schema='docs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_document_chunks_user_key'), table_name='document_chunks', schema='docs')
    op.drop_index(op.f('ix_docs_document_chunks_document_id'), table_name='document_chunks', schema='docs')
    op.drop_index('ix_chunks_user_document', table_name='document_chunks', schema='docs')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', schema='docs', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks', schema='docs')
    op.drop_index('ix_documents_user_kind', table_name='documents', schema='docs')
    op.drop_index(op.f('ix_docs_documents_user_key'), table_name='documents', schema='docs')
    op.drop_index(op.f('ix_docs_documents_status'), table_name='documents', schema='docs')
    op.drop_index(op.f('ix_docs_documents_sha256'), table_name='documents', schema='docs')
    op.drop_table('documents', schema='docs')
    # ### end Alembic commands ###
