"""rag service initial

Revision ID: 988dc5080658
Revises: 
Create Date: 2026-09-22 18:55:19.514705
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '988dc5080658'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_key', sa.String(length=320), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_key', 'updated_at'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_conversations_user_key'), 'conversations', ['user_key'], unique=False, schema='rag')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_mode', sa.String(length=8), nullable=False),
    sa.Column('used_reasoning', sa.Boolean(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('search_queries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='rag')
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_title', sa.String(length=500), nullable=False),
    sa.Column('document_kind', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['rag.messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_citations_message_id'), 'citations', ['message_id'], unique=False, schema='rag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_citations_message_id'), table_name='citations', schema='rag')
    op.drop_table('citations', schema='rag')
    op.drop_index(op.f('ix_rag_messages_conversation_id'), table_name='messages', schema='rag')
    op.drop_table('messages', schema='rag')
    op.drop_index(op.f('ix_rag_conversations_user_key'), table_name='conversations', schema='rag')
    op.drop_index('ix_conversations_user_updated', table_name='conversations', schema='rag')
    op.drop_table('conversations', schema='rag')
    # ### end Alembic commands ###
