"""web sources and opportunity context

Revision ID: d30028d4dba4
Revises: 988dc5080658
Create Date: 2026-09-22 20:41:26.769486
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'd30028d4dba4'
down_revision: str | None = '988dc5080658'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['rag.messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_web_sources_message_id'), 'web_sources', ['message_id'], unique=False, schema='rag')
    op.add_column('conversations', sa.Column('opportunity_id', sa.UUID(), nullable=True), schema='rag')
    op.add_column('conversations', sa.Column('opportunity_title', sa.String(length=500), nullable=True), schema='rag')
    op.add_column('messages', sa.Column('used_web', sa.Boolean(), nullable=False), schema='rag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'used_web', schema='rag')
    op.drop_column('conversations', 'opportunity_title', schema='rag')
    op.drop_column('conversations', 'opportunity_id', schema='rag')
    op.drop_index(op.f('ix_rag_web_sources_message_id'), table_name='web_sources', schema='rag')
    op.drop_table('web_sources', schema='rag')
    # ### end Alembic commands ###
