"""user preference regions

Revision ID: e512b010eca1
Revises: e041c5113108
Create Date: 2026-09-22 19:20:38.364223
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e512b010eca1'
down_revision: str | None = 'e041c5113108'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a value before the NOT NULL can hold, so add the column
    # with a server default, then drop the default so the ORM stays authoritative.
    op.add_column(
        'user_preferences',
        sa.Column(
            'regions',
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default='{}',
        ),
    )
    op.alter_column('user_preferences', 'regions', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'regions')
    # ### end Alembic commands ###
